{{
    config(
        unique_key='listing_id'
    )
}}

with check_dimensions as
(select
	case when listing_id in (select distinct listing_id from {{ ref('property_stg') }}) then listing_id else 0 end as listing_id,
	case when LISTING_NEIGHBOURHOOD in (select distinct SUBURB_NAME from {{ ref('lga_suburb_stg') }}) then LISTING_NEIGHBOURHOOD else 'unknown' end as LISTING_NEIGHBOURHOOD,
	case when HOST_ID in (select distinct HOST_ID from {{ ref('host_info_stg') }}) then HOST_ID else 0 end as HOST_ID,
	DATE,
	PRICE,
	HAS_AVAILABILITY,
	AVAILABILITY_30,
	NUMBER_OF_REVIEWS,
	REVIEW_SCORES_RATING,
	REVIEW_SCORES_ACCURACY,
	REVIEW_SCORES_CLEANLINESS,
	REVIEW_SCORES_CHECKIN,
	REVIEW_SCORES_COMMUNICATION,
	REVIEW_SCORES_VALUE
from {{ ref('listing_stg') }})

select
	a.listing_id,
	a.LISTING_NEIGHBOURHOOD,
	a.DATE,
	a.PRICE,
	a.HAS_AVAILABILITY,
	a.AVAILABILITY_30,
	a.NUMBER_OF_REVIEWS,
	a.REVIEW_SCORES_RATING,
	a.REVIEW_SCORES_ACCURACY,
	a.REVIEW_SCORES_CLEANLINESS,
	a.REVIEW_SCORES_CHECKIN,
	a.REVIEW_SCORES_COMMUNICATION,
	a.REVIEW_SCORES_VALUE,
	b.HOST_NAME,
    b.HOST_SINCE,
    b.HOST_IS_SUPERHOST,
    b.HOST_NEIGHBOURHOOD,
	c.PROPERTY_TYPE,
    c.ROOM_TYPE,
    c.ACCOMMODATES,
    g1.Tot_P_M,
	g1.Tot_P_F,
	g1.Tot_P_P,
	g1.Age_0_4_yr_M,
	g1.Age_0_4_yr_F,
	g1.Age_0_4_yr_P,
	g1.Age_5_14_yr_M,
	g1.Age_5_14_yr_F,
	g1.Age_5_14_yr_P,
	g1.Age_15_19_yr_M,
	g1.Age_15_19_yr_F,
	g1.Age_15_19_yr_P,
	g1.Age_20_24_yr_M,
	g1.Age_20_24_yr_F,
	g1.Age_20_24_yr_P,
	g1.Age_25_34_yr_M,
	g1.Age_25_34_yr_F,
	g1.Age_25_34_yr_P,
	g1.Age_35_44_yr_M,
	g1.Age_35_44_yr_F,
	g1.Age_35_44_yr_P,
	g1.Age_45_54_yr_M,
	g1.Age_45_54_yr_F,
	g1.Age_45_54_yr_P,
	g1.Age_55_64_yr_M,
	g1.Age_55_64_yr_F,
	g1.Age_55_64_yr_P,
	g1.Age_65_74_yr_M,
	g1.Age_65_74_yr_F,
	g1.Age_65_74_yr_P,
	g1.Age_75_84_yr_M,
	g1.Age_75_84_yr_F,
	g1.Age_75_84_yr_P,
	g1.Age_85ov_M,
	g1.Age_85ov_F,
	g1.Age_85ov_P,
	g1.Counted_Census_Night_home_M,
	g1.Counted_Census_Night_home_F,
	g1.Counted_Census_Night_home_P,
	g1.Count_Census_Nt_Ewhere_Aust_M,
	g1.Count_Census_Nt_Ewhere_Aust_F,
	g1.Count_Census_Nt_Ewhere_Aust_P,
	g1.Indigenous_psns_Aboriginal_M,
	g1.Indigenous_psns_Aboriginal_F,
	g1.Indigenous_psns_Aboriginal_P,
	g1.Indig_psns_Torres_Strait_Is_M,
	g1.Indig_psns_Torres_Strait_Is_F,
	g1.Indig_psns_Torres_Strait_Is_P,
	g1.Indig_Bth_Abor_Torres_St_Is_M,
	g1.Indig_Bth_Abor_Torres_St_Is_F,
	g1.Indig_Bth_Abor_Torres_St_Is_P,
	g1.Indigenous_P_Tot_M,
	g1.Indigenous_P_Tot_F,
	g1.Indigenous_P_Tot_P,
	g1.Birthplace_Australia_M,
	g1.Birthplace_Australia_F,
	g1.Birthplace_Australia_P,
	g1.Birthplace_Elsewhere_M,
	g1.Birthplace_Elsewhere_F,
	g1.Birthplace_Elsewhere_P,
	g1.Lang_spoken_home_Eng_only_M,
	g1.Lang_spoken_home_Eng_only_F,
	g1.Lang_spoken_home_Eng_only_P,
	g1.Lang_spoken_home_Oth_Lang_M,
	g1.Lang_spoken_home_Oth_Lang_F,
	g1.Lang_spoken_home_Oth_Lang_P,
	g1.Australian_citizen_M,
	g1.Australian_citizen_F,
	g1.Australian_citizen_P,
	g1.Age_psns_att_educ_inst_0_4_M,
	g1.Age_psns_att_educ_inst_0_4_F,
	g1.Age_psns_att_educ_inst_0_4_P,
	g1.Age_psns_att_educ_inst_5_14_M,
	g1.Age_psns_att_educ_inst_5_14_F,
	g1.Age_psns_att_educ_inst_5_14_P,
	g1.Age_psns_att_edu_inst_15_19_M,
	g1.Age_psns_att_edu_inst_15_19_F,
	g1.Age_psns_att_edu_inst_15_19_P,
	g1.Age_psns_att_edu_inst_20_24_M,
	g1.Age_psns_att_edu_inst_20_24_F,
	g1.Age_psns_att_edu_inst_20_24_P,
	g1.Age_psns_att_edu_inst_25_ov_M,
	g1.Age_psns_att_edu_inst_25_ov_F,
	g1.Age_psns_att_edu_inst_25_ov_P,
	g1.High_yr_schl_comp_Yr_12_eq_M,
	g1.High_yr_schl_comp_Yr_12_eq_F,
	g1.High_yr_schl_comp_Yr_12_eq_P,
	g1.High_yr_schl_comp_Yr_11_eq_M,
	g1.High_yr_schl_comp_Yr_11_eq_F,
	g1.High_yr_schl_comp_Yr_11_eq_P,
	g1.High_yr_schl_comp_Yr_10_eq_M,
	g1.High_yr_schl_comp_Yr_10_eq_F,
	g1.High_yr_schl_comp_Yr_10_eq_P,
	g1.High_yr_schl_comp_Yr_9_eq_M,
	g1.High_yr_schl_comp_Yr_9_eq_F,
	g1.High_yr_schl_comp_Yr_9_eq_P,
	g1.High_yr_schl_comp_Yr_8_belw_M,
	g1.High_yr_schl_comp_Yr_8_belw_F,
	g1.High_yr_schl_comp_Yr_8_belw_P,
	g1.High_yr_schl_comp_D_n_g_sch_M,
	g1.High_yr_schl_comp_D_n_g_sch_F,
	g1.High_yr_schl_comp_D_n_g_sch_P,
	g1.Count_psns_occ_priv_dwgs_M,
	g1.Count_psns_occ_priv_dwgs_F,
	g1.Count_psns_occ_priv_dwgs_P,
	g1.Count_Persons_other_dwgs_M,
	g1.Count_Persons_other_dwgs_F,
	g1.Count_Persons_other_dwgs_P,
    g2.Median_age_persons,
	g2.Median_mortgage_repay_monthly,
	g2.Median_tot_prsnl_inc_weekly,
	g2.Median_rent_weekly,
	g2.Median_tot_fam_inc_weekly,
	g2.Average_num_psns_per_bedroom,
	g2.Median_tot_hhd_inc_weekly,
	g2.Average_household_size
from check_dimensions as a
lEFT JOIN staging.host_info_stg as b on a.host_id = b.host_id and a.DATE::timestamp between b.dbt_valid_from and coalesce(to_timestamp(b.dbt_valid_to, 'YYYY-MM-DD HH24:MI:SS'), '9999-12-31 23:59:59'::timestamp)
LEFT JOIN staging.property_stg as c on a.listing_id = c.listing_id and a.DATE::timestamp between b.dbt_valid_from and coalesce(to_timestamp(b.dbt_valid_to, 'YYYY-MM-DD HH24:MI:SS'), '9999-12-31 23:59:59'::timestamp)
LEFT JOIN staging.lga_suburb_stg AS d ON a.LISTING_NEIGHBOURHOOD = d.SUBURB_NAME
LEFT JOIN staging.lga_code_stg AS e ON e.LGA_NAME = d.LGA_NAME 
LEFT JOIN staging.census_g01_stg AS g1 ON e.LGA_CODE = g1.LGA_CODE
LEFT JOIN staging.census_g02_stg AS g2 ON e.LGA_CODE = g2.LGA_CODE




